services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8086:8086
    volumes:
      - ./providers.toml:/app/providers.toml
      - ./__db:/root/.local/share/ccproxy/
